"""add_users_table

Revision ID: cef43be9a050
Revises: 
Create Date: 2026-03-15 12:33:02.706941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef43be9a050'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('capabilities', sa.Text(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('last_seen', sa.String(), nullable=True),
    sa.Column('task_count', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('failed_tasks', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('avg_response_time', sa.Float(), nullable=False),
    sa.Column('avg_task_duration', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index('idx_departments_name', ['name'], unique=False)
        batch_op.create_index('idx_departments_parent_id', ['parent_id'], unique=False)

    op.create_table('gateway_bridges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bridge_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('node_version', sa.String(length=50), nullable=True),
    sa.Column('bridge_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen', sa.Integer(), nullable=False),
    sa.Column('available_adapters', sa.JSON(), nullable=False),
    sa.Column('active_tasks', sa.Integer(), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bridge_id')
    )
    with op.batch_alter_table('gateway_bridges', schema=None) as batch_op:
        batch_op.create_index('idx_gateway_bridges_bridge_id', ['bridge_id'], unique=True)
        batch_op.create_index('idx_gateway_bridges_last_seen', ['last_seen'], unique=False)
        batch_op.create_index('idx_gateway_bridges_status', ['status'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('idx_roles_code', ['code'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('max_agents', sa.Integer(), nullable=False),
    sa.Column('max_projects', sa.Integer(), nullable=False),
    sa.Column('max_tasks', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('workflow_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_templates', schema=None) as batch_op:
        batch_op.create_index('idx_workflow_templates_category_created_at', ['category', 'created_at'], unique=False)

    op.create_table('agent_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata_', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_logs', schema=None) as batch_op:
        batch_op.create_index('idx_agent_logs_agent_id_created_at', ['agent_id', 'created_at'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('current_cost', sa.Float(), nullable=False),
    sa.Column('is_triggered', sa.Boolean(), nullable=False),
    sa.Column('threshold_percentage', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index('idx_budgets_agent_id_created_at', ['agent_id', 'created_at'], unique=False)
        batch_op.create_index('idx_budgets_status_created_at', ['status', 'created_at'], unique=False)

    op.create_table('gateway_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('bridge_id', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('project_path', sa.Text(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('preferred_ide', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('callback_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('changed_files', sa.JSON(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bridge_id'], ['gateway_bridges.bridge_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    with op.batch_alter_table('gateway_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_gateway_tasks_bridge_id', ['bridge_id'], unique=False)
        batch_op.create_index('idx_gateway_tasks_status', ['status'], unique=False)
        batch_op.create_index('idx_gateway_tasks_submitted_at', ['submitted_at'], unique=False)
        batch_op.create_index('idx_gateway_tasks_task_id', ['task_id'], unique=True)

    op.create_table('heartbeats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('last_run_at', sa.String(), nullable=True),
    sa.Column('next_run_at', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('action_params', sa.Text(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('heartbeats', schema=None) as batch_op:
        batch_op.create_index('idx_heartbeats_agent_id_created_at', ['agent_id', 'created_at'], unique=False)
        batch_op.create_index('idx_heartbeats_status_created_at', ['status', 'created_at'], unique=False)

    op.create_table('members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index('idx_members_department_id', ['department_id'], unique=False)
        batch_op.create_index('idx_members_email', ['email'], unique=False)

    op.create_table('org_chart_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('children_ids', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['org_chart_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_chart_nodes', schema=None) as batch_op:
        batch_op.create_index('idx_org_chart_nodes_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_org_chart_nodes_parent_id', ['parent_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assignee_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('action_params', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_agent_id_created_at', ['agent_id', 'created_at'], unique=False)
        batch_op.create_index('idx_tasks_status_created_at', ['status', 'created_at'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('requester_id', sa.String(), nullable=False),
    sa.Column('approver_ids', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('metadata_', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index('idx_approvals_requester_id_created_at', ['requester_id', 'created_at'], unique=False)
        batch_op.create_index('idx_approvals_status_created_at', ['status', 'created_at'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_logs_member_id_created_at', ['member_id', 'created_at'], unique=False)
        batch_op.create_index('idx_audit_logs_resource', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index('idx_audit_logs_resource_type_created_at', ['resource_type', 'created_at'], unique=False)

    op.create_table('cost_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('budget_id', sa.String(), nullable=False),
    sa.Column('current_cost', sa.Float(), nullable=False),
    sa.Column('threshold_percentage', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_alerts', schema=None) as batch_op:
        batch_op.create_index('idx_cost_alerts_budget_id_created_at', ['budget_id', 'created_at'], unique=False)

    op.create_table('cost_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('metadata_', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_entries', schema=None) as batch_op:
        batch_op.create_index('idx_cost_entries_agent_id_timestamp', ['agent_id', 'timestamp'], unique=False)

    op.create_table('daily_costs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('budget_id', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_costs', schema=None) as batch_op:
        batch_op.create_index('idx_daily_costs_agent_id_date', ['agent_id', 'date'], unique=False)
        batch_op.create_index('idx_daily_costs_budget_id_date', ['budget_id', 'date'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('target_date', sa.String(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index('idx_goals_department_id_created_at', ['department_id', 'created_at'], unique=False)
        batch_op.create_index('idx_goals_owner_id_created_at', ['owner_id', 'created_at'], unique=False)

    op.create_table('heartbeat_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('heartbeat_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['heartbeat_id'], ['heartbeats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('heartbeat_logs', schema=None) as batch_op:
        batch_op.create_index('idx_heartbeat_logs_heartbeat_id_started_at', ['heartbeat_id', 'started_at'], unique=False)

    op.create_table('task_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_task_assignments_task_id_agent_id', ['task_id', 'agent_id'], unique=False)

    op.create_table('workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index('idx_workflows_created_at', ['created_at'], unique=False)

    op.create_table('approval_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('approval_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_history', schema=None) as batch_op:
        batch_op.create_index('idx_approval_history_approval_id_created_at', ['approval_id', 'created_at'], unique=False)

    op.create_table('goal_alignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('alignment_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_alignments', schema=None) as batch_op:
        batch_op.create_index('idx_goal_alignments_child_id', ['child_id'], unique=False)
        batch_op.create_index('idx_goal_alignments_parent_id', ['parent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_alignments', schema=None) as batch_op:
        batch_op.drop_index('idx_goal_alignments_parent_id')
        batch_op.drop_index('idx_goal_alignments_child_id')

    op.drop_table('goal_alignments')
    with op.batch_alter_table('approval_history', schema=None) as batch_op:
        batch_op.drop_index('idx_approval_history_approval_id_created_at')

    op.drop_table('approval_history')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index('idx_workflows_created_at')

    op.drop_table('workflows')
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_task_assignments_task_id_agent_id')

    op.drop_table('task_assignments')
    with op.batch_alter_table('heartbeat_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_heartbeat_logs_heartbeat_id_started_at')

    op.drop_table('heartbeat_logs')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index('idx_goals_owner_id_created_at')
        batch_op.drop_index('idx_goals_department_id_created_at')

    op.drop_table('goals')
    with op.batch_alter_table('daily_costs', schema=None) as batch_op:
        batch_op.drop_index('idx_daily_costs_budget_id_date')
        batch_op.drop_index('idx_daily_costs_agent_id_date')

    op.drop_table('daily_costs')
    with op.batch_alter_table('cost_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_cost_entries_agent_id_timestamp')

    op.drop_table('cost_entries')
    with op.batch_alter_table('cost_alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_cost_alerts_budget_id_created_at')

    op.drop_table('cost_alerts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_logs_resource_type_created_at')
        batch_op.drop_index('idx_audit_logs_resource')
        batch_op.drop_index('idx_audit_logs_member_id_created_at')

    op.drop_table('audit_logs')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index('idx_approvals_status_created_at')
        batch_op.drop_index('idx_approvals_requester_id_created_at')

    op.drop_table('approvals')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_status_created_at')
        batch_op.drop_index('idx_tasks_agent_id_created_at')

    op.drop_table('tasks')
    with op.batch_alter_table('org_chart_nodes', schema=None) as batch_op:
        batch_op.drop_index('idx_org_chart_nodes_parent_id')
        batch_op.drop_index('idx_org_chart_nodes_created_at')

    op.drop_table('org_chart_nodes')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index('idx_members_email')
        batch_op.drop_index('idx_members_department_id')

    op.drop_table('members')
    with op.batch_alter_table('heartbeats', schema=None) as batch_op:
        batch_op.drop_index('idx_heartbeats_status_created_at')
        batch_op.drop_index('idx_heartbeats_agent_id_created_at')

    op.drop_table('heartbeats')
    with op.batch_alter_table('gateway_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_gateway_tasks_task_id')
        batch_op.drop_index('idx_gateway_tasks_submitted_at')
        batch_op.drop_index('idx_gateway_tasks_status')
        batch_op.drop_index('idx_gateway_tasks_bridge_id')

    op.drop_table('gateway_tasks')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index('idx_budgets_status_created_at')
        batch_op.drop_index('idx_budgets_agent_id_created_at')

    op.drop_table('budgets')
    with op.batch_alter_table('agent_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_agent_logs_agent_id_created_at')

    op.drop_table('agent_logs')
    with op.batch_alter_table('workflow_templates', schema=None) as batch_op:
        batch_op.drop_index('idx_workflow_templates_category_created_at')

    op.drop_table('workflow_templates')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_users_email')

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('idx_roles_code')

    op.drop_table('roles')
    with op.batch_alter_table('gateway_bridges', schema=None) as batch_op:
        batch_op.drop_index('idx_gateway_bridges_status')
        batch_op.drop_index('idx_gateway_bridges_last_seen')
        batch_op.drop_index('idx_gateway_bridges_bridge_id')

    op.drop_table('gateway_bridges')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index('idx_departments_parent_id')
        batch_op.drop_index('idx_departments_name')

    op.drop_table('departments')
    op.drop_table('agents')
    # ### end Alembic commands ###
